name: 'CodeThreat Scanner'
description: 'CodeThreat Scanner supports a variety of languages and providing detailed security scans to identify potential issues.'
author: 'CodeThreat, Inc'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  FAILED_ARGS:
    description: 'FAILED_ARGS'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'
  
